spring:
  application:
    name: products
  config:
    import: 
      - optional:classpath:.env[.properties]
      - "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
